# Generated by Django 3.0.8 on 2020-08-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlistssme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
