# Generated by Django 3.0.8 on 2020-08-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_addcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='addbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('user', models.CharField(max_length=64)),
            ],
        ),
    ]
