# Generated by Django 3.0.8 on 2020-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bidwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidwinner',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
