# Generated by Django 3.0.8 on 2020-08-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200813_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidwinner',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
