# Generated by Django 3.0.8 on 2020-08-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200813_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidwinner',
            name='title',
        ),
    ]
